name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate .xcodeproj
        run: xcodegen generate

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Package IPA manually
        run: |
          mkdir -p build/ipa/Payload
          cp -r build/CashBox.xcarchive/Products/Applications/CashBox.app build/ipa/Payload/
          cd build/ipa
          zip -r CashBox.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: CashBox-IPA
          path: build/ipa/CashBox.ipa
